# Site settings
title: F5 OpenStack
description: OpenStack solutions from F5 Networks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jodietestsite.s3-website-us-west-2.amazonaws.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
