# Site settings
title: F5 OpenStack
description: Uniquely cloud-ready
baseurl: "/f5-openstack-docs" # the subpath of your site, e.g. /blog/
url: "http://F5Networks.github.io" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap
  - github-pages

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
highlighter: pygments
exclude: [vendor, deprecated, Gemfile, Gemfile.lock, Rakefile]

kramdown:
    input: GFM

# Custom vars
current_version: 1.0.0
repo: https://github.com/F5Networks/f5-openstack-docs
brand: F5 Networks
github_username: F5Networks
sub_url1: f5-os-lbaasv1

# Categories
project-list: [lbaasv1, agent, odk, onboarding, misc_docs]
